version: '3.8'
services:
  client-frontend:
    image: frontend:0.0.1
    build:
      context: ../movie-review-fr
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:8080"

  backend:
    image: backend:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - database
    environment:
      - SERVER_PORT = 8000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/movie-review

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '15432:5432'
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: